config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resource :session, only: [:new, :create, :destroy]
  resources :comments
  resources :gossips do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :new, :create]
  resources :cities, only: [:show]
  get "welcome/:user_name", to: 'welcome#hello', as: 'welcome'
  get "/contact", to: 'pages#contact'
  get "/team", to: 'pages#team'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates :name, presence: true, uniqueness: true
  validates :zip_code, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :gossip_tags, dependent: :destroy
  has_many :tags, through: :gossip_tags
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  accepts_nested_attributes_for :tags
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :user_id, uniqueness: {scope: :gossip_id}
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :recipients
  has_many :users, through: :recipients
  validates :content, presence: true
  validates :sender_id, presence: true
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :recipients
  has_many :received_messages, through: :recipients, source: :private_message
  has_many :likes, dependent: :destroy
  has_many :liked_gossips, through: :likes, source: :gossip
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 18 }
  validates :city, presence: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user, only: [:new, :edit, :update, :create]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @gossip = @comment.gossip
  end

  # POST /comments or /comments.json
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to gossip_path(@gossip), notice: "Commentaire ajouté !"
    else
      redirect_to gossip_path(@gossip), alert: "Erreur : impossible d’ajouter le commentaire."
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
      if @comment.update(comment_params)
        redirect_to gossip_path(@comment.gossip), notice: "Le commentaire a été mis à jour avec succès"
      else
        flash.now[:alert] = "Erreur : veuillez remplir tous les champs correctement."
        render :edit
      end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @gossip = @comment.gossip
    @comment.destroy!
    redirect_to gossip_path(@gossip), notice: "Le commentaire a été supprimé avec succès."  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      # params.expect(comment: [ :content, :user_id, :gossip_id ])
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    @gossip = Gossip.find(params[:gossip_id])
    like = @gossip.likes.build(user: current_user)

    if like.save
      redirect_back fallback_location: root_path
    else
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    like = @gossip.likes.find_by(user: current_user)
    like.destroy if like
    redirect_back fallback_location: root_path
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
      
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && user.remember_digest.present? && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end


  def log_in(user)
    session[:user_id] = user.id
  end

  
  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64

    # j'ai mon token, je vais stocker son digest en base de données :
    user.remember(remember_token)

    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)

    user.update(remember_digest: nil)

    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Gossip:</strong>
    <%= comment.gossip_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :gossip_id, style: "display: block" %>
    <%= form.text_field :gossip_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Modifier le commentaire</h1>

<%= form_with model: @comment, local: true do |f| %>
    <div class="col-12">
      <%= f.text_area :content, class: "form-control", rows: 2 %>
      <div class="text-end mt-2">
        
        <%= f.submit "Modifier", class: "btn btn-secondary" %>
      </div>
    </div>
<% end %>
<%= button_to "supprimer", comment_path(@comment), method: :delete, data: {confirm: "Es-tu sur ?"}, class: "btn btn-danger" %>
<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Retour au gossip", gossip_path(@gossip) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<h1 class = "my-4">Commentaires par potin</h1>
  <%Gossip.all.each do |gossip|%>

    <%comments_nb = gossip.comments.count%>
    <div>
      <%= "#{gossip.title} a #{comments_nb}  #{comments_nb == 1 ? 'commentaire' : 'commentaires' }" %>
    </div>
  <% end %>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>